import { z } from "zod";

/** Plan §4.2. Persisted with a monotonic `seq`, mirrored to NDJSON, streamed over the Client API WebSocket. */
export const EventType = z.enum([
  "message.created",
  "message.delta",
  "message.completed",
  "message.held",
  "message.merged",
  "turn.queued",
  "turn.started",
  "turn.completed",
  "turn.failed",
  "turn.interrupted",
  "tool.started",
  "tool.completed",
  "action.simulated",
  "approval.requested",
  "approval.resolved",
  "input.requested",
  "input.answered",
  "input.dismissed",
  "input.cancelled",
  "handoff.sent",
  "handoff.received",
  "delegation.updated",
  "bot.created",
  "bot.updated",
  "bot.archived",
  "bot.archive_suggested",
  "route.decided",
  "gate.decided",
  "chain.limit_reached",
  "guard.tripped",
  "cap.hit",
  "chain.resumed",
  "chain.stopped",
  "attention.changed",
  "notify.requested",
  "digest.posted",
  "usage.recorded",
  "decision.made",
  "computer.status",
  "computer.image_status",
  "computer.task_started",
  "computer.step",
  "computer.escalated",
  "computer.takeover_requested",
  "computer.takeover_ended",
  "computer.task_completed",
  "routine.created",
  "routine.updated",
  "routine.deleted",
  "routine.paused",
  "routine.resumed",
  "trigger.received",
  "routine.run_queued",
  "routine.run_started",
  "routine.run_completed",
  "routine.run_skipped",
  "device.paired",
  "device.revoked",
  "remote.status",
  "connector.connected",
  "connector.disconnected",
  "setup.changed",
  "engine.status",
  "error",
]);
export type EventType = z.infer<typeof EventType>;

/** Untyped payload; `packages/contracts/fixtures/events/*.json` gives one worked example per event type for conformance/golden tests. */
export const OBEvent = z.object({
  id: z.string(),
  seq: z.number().int().nonnegative(),
  ts: z.string().datetime({ offset: true }),
  type: EventType,
  botId: z.string().optional(),
  threadId: z.string().optional(),
  turnId: z.string().optional(),
  chainId: z.string().optional(),
  payload: z.record(z.string(), z.unknown()),
});
export type OBEvent = z.infer<typeof OBEvent>;

export const EVENT_TYPES = EventType.options;
