name: Feature request
description: Suggest an improvement to OpenBot.
title: "feature: "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem should this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: What would you like OpenBot to do?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false
